version: '3.8'

services:
  orders-db:
    image: mongo:6.0
    container_name: orders_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - orders_mongo_data:/data/db
    ports:
      - "27017:27017"

  payments-db:
    image: postgres:15
    container_name: payments_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments_db
    volumes:
      - payments_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  products-db:
    image: postgres:15
    container_name: products_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    volumes:
      - products_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  users-db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  order-service:
    build: ./orders
    container_name: orders_service
    restart: always
    ports:
      - "3003:3000"
    environment:
      - DATABASE_URL=mongodb://orders-db:27017/orders_db
    depends_on:
      - orders-db

  product-service:
    build: ./products
    container_name: products_service
    restart: always
    ports:
      - "3004:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@products-db:5432/products_db
    depends_on:
      - products-db

  user-service:
    build: ./users
    container_name: users_service
    restart: always
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@users-db:5432/users_db
    depends_on:
      - users-db

  notification-service:
    build: ./notification
    container_name: notification_service
    restart: always
    ports:
      - "3007:3000"

  payment-service:
    build: ./payment
    container_name: payments_service
    restart: always
    ports:
      - "3006:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@payments-db:5432/payments_db
      - ORDER_API_URL=http://order-service:3000
      - PRODUCTS_API_URL=http://products-service:3000
      - NOTIFICATION_API_URL=http://notification-service:3000
    depends_on:
      - payments-db
      - order-service
      - product-service
      - notification-service

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - payments-db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: orders-db
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - orders-db
      
volumes:
  orders_mongo_data:
  products_postgres_data:
  users_postgres_data:
  payments_postgres_data:
  pgadmin_data: