
services:
  orders-db:
    image: mongo:6
    container_name: orders_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - orders_mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admin", "-p", "admin", "--authenticationDatabase", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payments-db:
    image: postgres:15
    container_name: payments_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments_db
    ports:
      - "5434:5432"
    volumes:
      - payments_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d payments_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  products-db:
    image: postgres:15
    container_name: products_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    ports:
      - "5435:5432"
    volumes:
      - products_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  users-db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./users
    container_name: user_service
    restart: always
    # ports:
    #   - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@users-db:5432/users_db
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      users-db:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm run start"

  product-service:
    build: ./products
    container_name: product_service
    restart: always
    # ports:
    #   - "3004:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@products-db:5432/products_db
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      products-db:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm run start"
    
  order-service:
    build: ./orders
    container_name: order_service
    restart: always
    # ports:
    #   - "3003:3000"
    environment:
      - DATABASE_URL=mongodb://admin:admin@orders-db:27017/orders_db?authSource=admin
      - PRODUCTS_API_URL=http://product-service:3000/api/products
      - PAYMENTS_API_URL=http://payment-service:3000/api/payments
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      orders-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    command: sh -c "npm run db:seed && npm run start"

  payment-service:
    build: ./payment
    container_name: payment_service
    restart: always
    # ports:
    #   - "3006:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@payments-db:5432/payments_db
      - ORDER_API_URL=http://order-service:3000/api/orders
      - PRODUCTS_API_URL=http://product-service:3000/api/products
      - USER_API_URL=http://user-service:3000/api/clients
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      payments-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      # Dependência para garantir a ordem correta do SEEDING
      order-service:
        condition: service_started
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm run start"
    
  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_lab
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    depends_on:
      - redis-cache


  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-service:
    build: ./notification
    container_name: notification_service
    restart: always
    # ports:
    #   - "3007:3000"
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
    healthcheck:
      # TRUQUE: Usamos 'nc' (netcat) para enviar "ruok". Se responder "imok", está saudável.
      # Isso gasta 0 de memória comparado ao 'cub'
      test: echo ruok | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
      
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - payments-db
      - products-db
      - users-db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: orders-db
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - orders-db

  kong-db:
    image: postgres:15
    container_name: kong_db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong_password
      POSTGRES_DB: kong
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  kong-migration:
    image: kong:3.4
    container_name: kong_migration
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
    command: "kong migrations bootstrap"
    depends_on:
      - kong-db

  kong-gateway:
    image: kong:3.4
    container_name: kong_gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-migration

  konga:
    image: pantsel/konga
    container_name: konga_ui
    restart: always
    environment:
      NODE_ENV: development
      KONGA_KONG_ADMIN_URL: http://kong-gateway:8001
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway

volumes:
  orders_mongo_data:
  products_postgres_data:
  users_postgres_data:
  payments_postgres_data:
  pgadmin_data:
  redis_data:
  kong_postgres_data: